version: '3.1'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env

  spiders:
    build: 
      context: .
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
        - db 
