version: '3.1'

services:
  db:
    image: postgres:11.22-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  spiders:
    build: 
      context: .
    command: >
      sh -c "python3 parser.py"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
        - db
