"""Migrations with main tables

Revision ID: 11578cfee2e4
Revises: 18afd0c8c8e1
Create Date: 2024-02-28 12:48:35.174215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11578cfee2e4'
down_revision: Union[str, None] = '18afd0c8c8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
